-- Nur in den beiden leeren Testschema ORACMP_REF und ORACMP_TARGET ausführen.
-- Schemaerstellung, Rechte und Quotas werden von der Testumgebung bereitgestellt.
SET DEFINE OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE SEQUENCE ORACMP_REF.ID_SEQ START WITH 100 INCREMENT BY 1 CACHE 50;
CREATE SEQUENCE ORACMP_TARGET.ID_SEQ START WITH 20 INCREMENT BY 1 CACHE 20;

CREATE TABLE ORACMP_REF.PARENT (
  ID NUMBER DEFAULT ORACMP_REF.ID_SEQ.NEXTVAL,
  LABEL VARCHAR2(60 CHAR),
  CONSTRAINT PARENT_PK PRIMARY KEY (ID)
);
CREATE TABLE ORACMP_TARGET.PARENT (
  ID NUMBER DEFAULT ORACMP_TARGET.ID_SEQ.NEXTVAL,
  LABEL VARCHAR2(30 CHAR),
  CONSTRAINT PARENT_PK PRIMARY KEY (ID)
);

CREATE TABLE ORACMP_REF.CHILD (
  ID NUMBER,
  PARENT_ID NUMBER,
  LABEL VARCHAR2(60 CHAR),
  CONSTRAINT CHILD_PK PRIMARY KEY (ID),
  CONSTRAINT CHILD_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES ORACMP_REF.PARENT(ID)
);
CREATE TABLE ORACMP_TARGET.CHILD (
  ID NUMBER,
  PARENT_ID NUMBER,
  LABEL VARCHAR2(60 CHAR),
  CONSTRAINT CHILD_PK PRIMARY KEY (ID),
  CONSTRAINT CHILD_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES ORACMP_TARGET.PARENT(ID)
);
CREATE INDEX ORACMP_REF.CHILD_IX ON ORACMP_REF.CHILD(PARENT_ID, LABEL);
CREATE INDEX ORACMP_TARGET.CHILD_IX ON ORACMP_TARGET.CHILD(PARENT_ID);

-- Schemaweiter Namenswechsel: B muss CK_MOVED vor der Anlage auf A freigeben.
-- Die gleichzeitige Spaltenänderung prüft gemischte ALTER_XML-Operationen.
CREATE TABLE ORACMP_REF.MOVE_A (
  VALUE NUMBER, LABEL VARCHAR2(60 CHAR),
  CONSTRAINT CK_MOVED CHECK (VALUE >= 0)
);
CREATE TABLE ORACMP_TARGET.MOVE_A (VALUE NUMBER, LABEL VARCHAR2(30 CHAR));
CREATE TABLE ORACMP_REF.MOVE_B (VALUE NUMBER, LABEL VARCHAR2(60 CHAR));
CREATE TABLE ORACMP_TARGET.MOVE_B (
  VALUE NUMBER, LABEL VARCHAR2(30 CHAR),
  CONSTRAINT CK_MOVED CHECK (VALUE >= 0)
);

-- Neue Tabellen: Die alphabetische Ausgabe A -> M -> Z verläuft entgegen der FK-Kette.
-- Z wird über einen Unique-Key referenziert; A referenziert außerdem sich selbst.
CREATE TABLE ORACMP_REF.Z_FK_ROOT (
  ID NUMBER, CODE NUMBER,
  CONSTRAINT Z_FK_ROOT_PK PRIMARY KEY (ID),
  CONSTRAINT Z_FK_ROOT_UK UNIQUE (CODE)
);
CREATE TABLE ORACMP_REF.M_FK_MIDDLE (
  ID NUMBER, ROOT_CODE NUMBER,
  CONSTRAINT M_FK_MIDDLE_PK PRIMARY KEY (ID),
  CONSTRAINT M_FK_ROOT_FK FOREIGN KEY (ROOT_CODE) REFERENCES ORACMP_REF.Z_FK_ROOT(CODE)
);
CREATE TABLE ORACMP_REF.A_FK_LEAF (
  ID NUMBER, MIDDLE_ID NUMBER, PARENT_ID NUMBER,
  CONSTRAINT A_FK_LEAF_PK PRIMARY KEY (ID),
  CONSTRAINT A_FK_MIDDLE_FK FOREIGN KEY (MIDDLE_ID) REFERENCES ORACMP_REF.M_FK_MIDDLE(ID),
  CONSTRAINT A_FK_SELF_FK FOREIGN KEY (PARENT_ID) REFERENCES ORACMP_REF.A_FK_LEAF(ID)
);

-- Gegenseitiger Zyklus: Beide Tabellen und ihre PKs müssen vor beiden FKs existieren.
CREATE TABLE ORACMP_REF.X_FK_CYCLE (
  ID NUMBER, Y_ID NUMBER, CONSTRAINT X_FK_CYCLE_PK PRIMARY KEY (ID)
);
CREATE TABLE ORACMP_REF.Y_FK_CYCLE (
  ID NUMBER, X_ID NUMBER, CONSTRAINT Y_FK_CYCLE_PK PRIMARY KEY (ID)
);
ALTER TABLE ORACMP_REF.X_FK_CYCLE ADD CONSTRAINT X_FK_Y_FK
  FOREIGN KEY (Y_ID) REFERENCES ORACMP_REF.Y_FK_CYCLE(ID);
ALTER TABLE ORACMP_REF.Y_FK_CYCLE ADD CONSTRAINT Y_FK_X_FK
  FOREIGN KEY (X_ID) REFERENCES ORACMP_REF.X_FK_CYCLE(ID);

CREATE VIEW ORACMP_REF.Z_PARENT_VIEW AS
  SELECT ID, LABEL, 'ORACMP_REF.PARENT' AS LITERAL_TEXT FROM ORACMP_REF.PARENT;
CREATE VIEW ORACMP_REF.A_PARENT_VIEW AS SELECT * FROM ORACMP_REF.Z_PARENT_VIEW;
CREATE VIEW ORACMP_TARGET.Z_PARENT_VIEW AS SELECT ID, LABEL FROM ORACMP_TARGET.PARENT;

CREATE TABLE ORACMP_REF.NEW_TABLE (ID NUMBER);
CREATE TABLE ORACMP_TARGET.EXTRA_TABLE (ID NUMBER);
CREATE INDEX ORACMP_TARGET.EXTRA_INDEX ON ORACMP_TARGET.CHILD(LABEL);
CREATE VIEW ORACMP_TARGET.EXTRA_VIEW AS SELECT * FROM ORACMP_TARGET.EXTRA_TABLE;
CREATE SEQUENCE ORACMP_TARGET.EXTRA_SEQ;

PROMPT Fixture angelegt. Jetzt ORACMP_TARGET an ORACMP_REF angleichen.
