-- Referenz-Fixture für eine eigene JDBC-Connection.
-- ${SCHEMA_IDENTIFIER} ersetzt der Java-Test durch den exakt gequoteten Connection-Schemanamen.
-- Nur in einem leeren Testschema ausführen; Oracle-DDL führt implizite Commits aus.

CREATE SEQUENCE ${SCHEMA_IDENTIFIER}.ID_SEQ START WITH 100 INCREMENT BY 1 CACHE 50;

CREATE TABLE ${SCHEMA_IDENTIFIER}.PARENT (
  ID NUMBER DEFAULT ${SCHEMA_IDENTIFIER}.ID_SEQ.NEXTVAL,
  LABEL VARCHAR2(60 CHAR),
  CONSTRAINT PARENT_PK PRIMARY KEY (ID)
);

CREATE TABLE ${SCHEMA_IDENTIFIER}.CHILD (
  ID NUMBER,
  PARENT_ID NUMBER,
  LABEL VARCHAR2(60 CHAR),
  CONSTRAINT CHILD_PK PRIMARY KEY (ID),
  CONSTRAINT CHILD_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES ${SCHEMA_IDENTIFIER}.PARENT(ID)
);

CREATE INDEX ${SCHEMA_IDENTIFIER}.CHILD_IX ON ${SCHEMA_IDENTIFIER}.CHILD(PARENT_ID, LABEL);

CREATE TABLE ${SCHEMA_IDENTIFIER}.MOVE_A (
  VALUE NUMBER, LABEL VARCHAR2(60 CHAR),
  CONSTRAINT CK_MOVED CHECK (VALUE >= 0)
);

CREATE TABLE ${SCHEMA_IDENTIFIER}.MOVE_B (VALUE NUMBER, LABEL VARCHAR2(60 CHAR));

CREATE TABLE ${SCHEMA_IDENTIFIER}.Z_FK_ROOT (
  ID NUMBER, CODE NUMBER,
  CONSTRAINT Z_FK_ROOT_PK PRIMARY KEY (ID),
  CONSTRAINT Z_FK_ROOT_UK UNIQUE (CODE)
);

CREATE TABLE ${SCHEMA_IDENTIFIER}.M_FK_MIDDLE (
  ID NUMBER, ROOT_CODE NUMBER,
  CONSTRAINT M_FK_MIDDLE_PK PRIMARY KEY (ID),
  CONSTRAINT M_FK_ROOT_FK FOREIGN KEY (ROOT_CODE) REFERENCES ${SCHEMA_IDENTIFIER}.Z_FK_ROOT(CODE)
);

CREATE TABLE ${SCHEMA_IDENTIFIER}.A_FK_LEAF (
  ID NUMBER, MIDDLE_ID NUMBER, PARENT_ID NUMBER,
  CONSTRAINT A_FK_LEAF_PK PRIMARY KEY (ID),
  CONSTRAINT A_FK_MIDDLE_FK FOREIGN KEY (MIDDLE_ID) REFERENCES ${SCHEMA_IDENTIFIER}.M_FK_MIDDLE(ID),
  CONSTRAINT A_FK_SELF_FK FOREIGN KEY (PARENT_ID) REFERENCES ${SCHEMA_IDENTIFIER}.A_FK_LEAF(ID)
);

CREATE TABLE ${SCHEMA_IDENTIFIER}.X_FK_CYCLE (
  ID NUMBER, Y_ID NUMBER, CONSTRAINT X_FK_CYCLE_PK PRIMARY KEY (ID)
);

CREATE TABLE ${SCHEMA_IDENTIFIER}.Y_FK_CYCLE (
  ID NUMBER, X_ID NUMBER, CONSTRAINT Y_FK_CYCLE_PK PRIMARY KEY (ID)
);

ALTER TABLE ${SCHEMA_IDENTIFIER}.X_FK_CYCLE ADD CONSTRAINT X_FK_Y_FK
  FOREIGN KEY (Y_ID) REFERENCES ${SCHEMA_IDENTIFIER}.Y_FK_CYCLE(ID);

ALTER TABLE ${SCHEMA_IDENTIFIER}.Y_FK_CYCLE ADD CONSTRAINT Y_FK_X_FK
  FOREIGN KEY (X_ID) REFERENCES ${SCHEMA_IDENTIFIER}.X_FK_CYCLE(ID);

CREATE VIEW ${SCHEMA_IDENTIFIER}.Z_PARENT_VIEW AS
  SELECT ID, LABEL, 'Schema.PARENT bleibt ein Literal' AS LITERAL_TEXT FROM ${SCHEMA_IDENTIFIER}.PARENT;

CREATE VIEW ${SCHEMA_IDENTIFIER}.A_PARENT_VIEW AS SELECT * FROM ${SCHEMA_IDENTIFIER}.Z_PARENT_VIEW;

CREATE TABLE ${SCHEMA_IDENTIFIER}.NEW_TABLE (ID NUMBER);

-- Regressionen fuer Spaltenwechsel, virtuelle Abhaengigkeiten und READ ONLY.
CREATE TABLE ${SCHEMA_IDENTIFIER}.COLUMN_REPLACE (NEW_COL NUMBER);
CREATE TABLE ${SCHEMA_IDENTIFIER}.VIRTUAL_DROP (ID NUMBER);
CREATE TABLE ${SCHEMA_IDENTIFIER}.READ_ONLY_CHANGE (ID NUMBER) READ ONLY;
CREATE TABLE ${SCHEMA_IDENTIFIER}.READ_ONLY_KEEP (ID NUMBER) READ ONLY;
CREATE TABLE ${SCHEMA_IDENTIFIER}.LONG_CHANGE (ID NUMBER, NEW_COL LONG);

-- Neue Partitionierungsobjekte prüfen CREATE auf dem Ziel einschließlich ihrer Indizes.
-- Bestehende Partitionierungsstrategien werden in diesem Test nicht geändert.
CREATE TABLE ${SCHEMA_IDENTIFIER}.PART_RANGE_SALES (
  ID NUMBER, BOOKING_DATE DATE, REGION VARCHAR2(10 CHAR), AMOUNT NUMBER
)
PARTITION BY RANGE (BOOKING_DATE) (
  PARTITION P_2025 VALUES LESS THAN (DATE '2026-01-01'),
  PARTITION P_FUTURE VALUES LESS THAN (MAXVALUE)
);

CREATE INDEX ${SCHEMA_IDENTIFIER}.PART_RANGE_LOCAL_IX
  ON ${SCHEMA_IDENTIFIER}.PART_RANGE_SALES(REGION) LOCAL;

CREATE INDEX ${SCHEMA_IDENTIFIER}.PART_RANGE_GLOBAL_IX
  ON ${SCHEMA_IDENTIFIER}.PART_RANGE_SALES(ID)
  GLOBAL PARTITION BY RANGE (ID) (
    PARTITION P_SMALL VALUES LESS THAN (10000),
    PARTITION P_LARGE VALUES LESS THAN (MAXVALUE)
  );

CREATE INDEX ${SCHEMA_IDENTIFIER}.PART_HASH_GLOBAL_IX
  ON ${SCHEMA_IDENTIFIER}.PART_RANGE_SALES(AMOUNT)
  GLOBAL PARTITION BY HASH (AMOUNT) (
    PARTITION P_HASH_1,
    PARTITION P_HASH_2
  );

CREATE TABLE ${SCHEMA_IDENTIFIER}.PART_LIST_REGIONS (
  ID NUMBER, REGION VARCHAR2(10 CHAR), CUSTOMER_ID NUMBER
)
PARTITION BY LIST (REGION) (
  PARTITION P_EU VALUES ('EU'),
  PARTITION P_US VALUES ('US'),
  PARTITION P_OTHER VALUES (DEFAULT)
);

CREATE INDEX ${SCHEMA_IDENTIFIER}.PART_LIST_LOCAL_IX
  ON ${SCHEMA_IDENTIFIER}.PART_LIST_REGIONS(CUSTOMER_ID) LOCAL;
