-- Ziel-Fixture für eine eigene JDBC-Connection.
-- ${SCHEMA_IDENTIFIER} ersetzt der Java-Test durch den exakt gequoteten Connection-Schemanamen.
-- Nur in einem leeren Testschema ausführen; Oracle-DDL führt implizite Commits aus.

CREATE SEQUENCE ${SCHEMA_IDENTIFIER}.ID_SEQ START WITH 20 INCREMENT BY 1 CACHE 20;

CREATE TABLE ${SCHEMA_IDENTIFIER}.PARENT (
  ID NUMBER DEFAULT ${SCHEMA_IDENTIFIER}.ID_SEQ.NEXTVAL,
  LABEL VARCHAR2(30 CHAR),
  CONSTRAINT PARENT_PK PRIMARY KEY (ID)
);

CREATE TABLE ${SCHEMA_IDENTIFIER}.CHILD (
  ID NUMBER,
  PARENT_ID NUMBER,
  LABEL VARCHAR2(60 CHAR),
  CONSTRAINT CHILD_PK PRIMARY KEY (ID),
  CONSTRAINT CHILD_PARENT_FK FOREIGN KEY (PARENT_ID) REFERENCES ${SCHEMA_IDENTIFIER}.PARENT(ID)
);

CREATE INDEX ${SCHEMA_IDENTIFIER}.CHILD_IX ON ${SCHEMA_IDENTIFIER}.CHILD(PARENT_ID);

CREATE TABLE ${SCHEMA_IDENTIFIER}.MOVE_A (VALUE NUMBER, LABEL VARCHAR2(30 CHAR));

CREATE TABLE ${SCHEMA_IDENTIFIER}.MOVE_B (
  VALUE NUMBER, LABEL VARCHAR2(30 CHAR),
  CONSTRAINT CK_MOVED CHECK (VALUE >= 0)
);

CREATE VIEW ${SCHEMA_IDENTIFIER}.Z_PARENT_VIEW AS SELECT ID, LABEL FROM ${SCHEMA_IDENTIFIER}.PARENT;

CREATE TABLE ${SCHEMA_IDENTIFIER}.EXTRA_TABLE (ID NUMBER);

CREATE INDEX ${SCHEMA_IDENTIFIER}.EXTRA_INDEX ON ${SCHEMA_IDENTIFIER}.CHILD(LABEL);

CREATE VIEW ${SCHEMA_IDENTIFIER}.EXTRA_VIEW AS SELECT * FROM ${SCHEMA_IDENTIFIER}.EXTRA_TABLE;

CREATE SEQUENCE ${SCHEMA_IDENTIFIER}.EXTRA_SEQ;

-- Überzählige partitionierte Tabelle samt lokalem Index muss im Ziel verschwinden.
CREATE TABLE ${SCHEMA_IDENTIFIER}.EXTRA_PART_TABLE (ID NUMBER)
PARTITION BY RANGE (ID) (
  PARTITION P_FIRST VALUES LESS THAN (100),
  PARTITION P_LAST VALUES LESS THAN (MAXVALUE)
);

CREATE INDEX ${SCHEMA_IDENTIFIER}.EXTRA_PART_IX
  ON ${SCHEMA_IDENTIFIER}.EXTRA_PART_TABLE(ID) LOCAL;
